export const CartActionTypes = {
    TOGGLE_CARD_HIDDEN : 'TOGGLE_CARD_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CARD: 'CLEAR_ITEM_FROM_CARD',
    REMOVE_ITEM_QUANTITY: 'REMOVE_ITEM_QUANTITY'
}